name: Build Qt Application

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.11.1
          arch: clang_64
          cache: true

      - name: Configure
        run: |
          cmake \
            -S exercises/qt/new-pro \
            -B exercises/qt/new-pro/build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake \
            --build exercises/qt/new-pro/build \
            --config Release \
            --parallel

      - name: Deploy
        run: |
          macdeployqt \
            exercises/qt/new-pro/build/new-pro.app \
            -always-overwrite

      - name: Package
        run: |
          cd exercises/qt/new-pro/build
          zip -r ../../../../new-pro-macos.zip new-pro.app

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: new-pro-macos
          path: new-pro-macos.zip